apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch-chart.fullname" . }}
  labels:
    {{- include "quakewatch-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      {{- if (and (eq .Values.service.type "NodePort" )  (not (empty .Values.service.NodePort)))}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

      protocol: TCP
      name: http
  selector:
    {{- include "quakewatch-chart.selectorLabels" . | nindent 4 }}
