prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false # זה הכי חשוב! מונע את השגיאה שראינו

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 1d # שמירת נתונים ליום אחד בלבד
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

grafana:
  enabled: true
  adminPassword: admin # סיסמה פשוטה לכניסה
  persistence:
    enabled: false # לא שומר דאשבורדים אחרי מחיקה (חוסך מקום)

# מכבים את כל ה"רעש" מסביב שלא דחוף כרגע
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: true # זה חשוב כדי לראות את הסטטוס של האפליקציה שלך
kubeProxy:
  enabled: false